server:
  port: 8081

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:9949
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.229.11:3306/guli_pms
    username: root
    password: 12345
  redis:
    host: 192.168.229.11
mybatis-plus:
  mapper-locations: classpath:mapper/pms/**/*.xml
